

Import('env')

lib_src = ['Collision.cpp','CollisionData.cpp']
lib_target = 'collisions'

env.Append(CPPPATH = ['/opt/hfs13.0.582/toolkit/include/','/home/jaideep/CGAL-4.3/include'])
env.Append(CCFLAGS='-fPIC')
env.Append(CCFLAGS='-DSIZEOF_VOID_P=8')

lib = env.StaticLibrary(source = lib_src , target = lib_target)
