

Import('env')

lib_src = ['ForceFactory.cpp','NoiseForce.cpp','VDBForce.cpp']
lib_target = 'forces'

env.Append(CPPPATH = ['/opt/houdini/toolkit/include/'])
env.Append(CCFLAGS='-fPIC')
env.Append(CCFLAGS='-DSIZEOF_VOID_P=8')

lib = env.StaticLibrary(source = lib_src , target = lib_target)
