

Import('env')

lib_src = ['Source.cpp','SourceFactory.cpp','SphereSource.cpp','VDBSource.cpp','SoftBodySource.cpp','SoftBodyData.cpp']
lib_target = 'sources'

env.Append(CPPPATH = ['/opt/houdini/toolkit/include/','/home/jaideep/CGAL-4.3/include'])
env.Append(CCFLAGS='-fPIC')
env.Append(CCFLAGS='-DSIZEOF_VOID_P=8')
env.Append(CCFLAGS=['-Wno-attributes'])

lib = env.StaticLibrary(source = lib_src , target = lib_target)
