Import('env')


houdini_static_env = env.Clone()
houdini_shared_env = env.Clone()
base_types_env = env.Clone()
solver_env = env.Clone()
forces_env = env.Clone()
sources_env = env.Clone()
collisions_env = env.Clone()

SConscript('houdini/SConscript_Static', exports={'env':houdini_static_env})
SConscript('houdini/SConscript_Shared', exports={'env':houdini_shared_env})
SConscript('solver/SConscript', exports={'env':solver_env})
SConscript('forces/SConscript', exports={'env':forces_env})
SConscript('sources/SConscript', exports={'env':sources_env})
SConscript('collisions/SConscript', exports={'env':collisions_env})
